---
title: "Regression for Count"
author: "Mohd Azmi"
date: "20/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Environment

## Library

```{r}
library(pacman)
p_load(tidyverse, haven, broom, janitor, summarytools)
```

## Dataset

```{r}
publishds <- read_stata("couart2.dta")
publishds2 <- publishds %>% mutate_if(is.labelled, ~(as_factor(.)))
publishds2

data("NMES1988", package = "AER") #p_load(AER) - however edvisitds not used in this practical.
edvisitds <- NMES1988 %>% clean_names()
edvisitds
```

# Analysis

## Exploratory

```{r}
freq(publishds2)
descr(publishds2)
```

## Plot

### Article

```{r}
ggplot(publishds2, aes(art)) + geom_histogram(binwidth = 1) + scale_x_continuous(breaks = seq(0,20,1))
ggplot(publishds2, aes(art)) + geom_bar() + scale_x_continuous(breaks = seq(0,20,1))
ggplot(publishds2, aes(art)) + geom_density() + scale_x_continuous(breaks = seq(0,20,1)) 
```

## Poisson Regression

### Constant or minimal model

```{r}
art_minmod <- glm(art ~ 1, data = publishds2, family = poisson())
summary(art_minmod)
tidy(art_minmod) %>% mutate(llciest = estimate - 1.96 * std.error,
                            ulciest = estimate + 1.96 * std.error,
                            pred_freq = exp(estimate),
                            llci = exp(llciest),
                            ulci = exp(ulciest)) %>% 
  select(term, estimate, llciest, ulciest, pred_freq, llci, ulci, p.value)
mean(publishds2$art)
```


### Multivariable model

- IV - fem, mar, kid5, phd, ment -- all variable

```{r}
art_allmod <- glm(art ~ ., data = publishds2, family = poisson())
summary(art_allmod)
tidy(art_allmod, conf.int=T) %>% 
  mutate(pred_freq = exp(estimate),
         llci = exp(conf.low),
         ulci = exp(conf.high)) %>% 
  select(term, estimate, conf.low, conf.high, pred_freq, llci, ulci, p.value)
```

## Prediction

```{r}
augment(art_allmod, type.predict = "link") # log count
augment(art_allmod, type.predict = "response") # count
publish_longdts <- augment(art_allmod, type.predict = "term") # calculate ? for each iv

head(predict(art_allmod, type = "link"))
```

